### ISSUE TITLE
公式不是标准公式,用的什么公式?

### ISSUE THREAD

**Issue by WREQI** [yanceyou/bfgs-algorithm#1]
![image](https://user-images.githubusercontent.com/35467304/180952905-f587ad7a-4a6e-4be4-b1a5-362431d8ea7b.png)
![image](https://user-images.githubusercontent.com/35467304/180952977-ba627468-d41b-4415-811b-3ce87890fc7d.png)

**Comment by yanceyou** [comment]
都好久了，不太记得之前的逻辑了。大概也许可能应该是 [wiki 这个公式](https://en.wikipedia.org/wiki/Broyden%E2%80%93Fletcher%E2%80%93Goldfarb%E2%80%93Shanno_algorithm)：
![image](https://user-images.githubusercontent.com/16320418/181149706-59c87205-2888-4512-a9a6-17f2309c8603.png)
